version: '3'
services:
  course-rating-api:
    image: course-rating-api:latest
    container_name: course-rating-api
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./.env:/opt/app/.env
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - ./docker/mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
volumes:
  mongo-data:
