version: '3'
services:
  course-rating-api:
    image: course-rating-api:latest
    container_name: course-rating-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/opt/app/.env
